# Generated by Django 3.1.2 on 2021-06-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
