# Generated by Django 3.1.2 on 2021-06-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(default='')),
                ('Social', models.IntegerField(default=0)),
                ('Emotional', models.IntegerField(default=0)),
                ('Study', models.IntegerField(default=0)),
                ('Personal', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
