# Generated by Django 3.1.2 on 2021-06-26 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanges',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_challanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChallangeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Challange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_challanges', to='challanges.challanges')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_challanges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
