# Generated by Django 3.1.2 on 2021-08-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0004_completed_challange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanges',
            name='completed',
        ),
    ]
